### PR TITLE
update for glNext

### PR DESCRIPTION
**Pull request by MartinBspheroid**
This is not really optimal in terms of using `Rectf` for drawing graphs, because it drags overall performance down like a brick. But at least it compiles and we can work from this to something more usefull

### CODE REVIEW

**Comment by q-depot** [comment]
Hi Martin,

thanks for the update, I didn't touch this repository in a long time.
I actually moved to another library called Essentia.

**Comment by MartinBspheroid** [comment]
I see. No problem, I was about to check that one too and do some A-B testing.
Thanks

**Comment by q-depot** [comment]
I have a Cinder block for essentia that runs on osx, windows is a bit more tricky. I might share it soon if you are interested.

**Comment by MartinBspheroid** [comment]
Consider me interested :+1:

**Pull request merged**
